//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Credit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credits
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Credits()
        {
            this.PaymentSchedule = new HashSet<PaymentSchedule>();
        }
    
        public int Id { get; set; }
        public int ClientId { get; set; }
        public System.DateTime StartDate { get; set; }
        public double Amount { get; set; }
        public int Duration { get; set; }
        public double AnnualInterestRate { get; set; }
        public string Pledge { get; set; }
        public DateTime LastUpdated { get; set; }
        public bool IsOutdated { get; set; }
    
        public virtual Clients Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentSchedule> PaymentSchedule { get; set; }
    }
}
