//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Credit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentSchedule
    {
        public int Id { get; set; }
        public int CreditId { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public double Amount { get; set; }
        public double InterestRate { get; set; }
        public bool IsPaid { get; set; }
        public DateTime LastUpdated { get; set; }
    
        public virtual Credits Credits { get; set; }
    }
}
